name: Publish
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  publish_job:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Go To Omo-App
        run: cd omo-app
      - name: Setup Node
        uses: actions/setup-node@v2
      - run: npm run install
      - run: npm run build
      - uses: fission-suite/publish-action@v1
        with:
          machine_key: ${{ secrets.MACHINE_KEY }}
